### ISSUE TITLE
Change server port on test

### ISSUE THREAD

**Issue by joaopapereira** [AgileVentures/AsyncVoter#15]
Make the server port configurable to ensure that the tests and the server do not run in the same port

**Comment by joaopapereira** [comment]
@here :speaking_head_in_silhouette:  _Result *[ASYNC VOTE]* on:_ https://waffle.io/AgileVentures/AsyncVoter/cards/58121220d31ebe1300e97b1f `Change server port on test`. 4 vote so far from *[* @edmilsonefs @sysrex @zsuark @jnr.gonzalez *]*

**Comment by joaopapereira** [comment]
Suggestion by @juniorg:
We can set up a 'PORT' env variable and have our app read it when testing

**Comment by krauszraphael** [comment]
Wouldn't it be better to have a config file in the project directory, where the server port and the testing port is defined?

**Comment by sysrex** [comment]
I suggest to use dotenv, and in the project we will have a .env file with the database configuration and the port , not all of use use the same setup and it would make life easier, also in the future the api keys for testing should be there, everything that is env related ...and that we do not want to share on github
