### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by joaopapereira** [AgileVentures/AsyncVoter#21]
Readme still says:
To run all the tests execute

npm run spec

Instead of 
npm test

**Comment by krauszraphael** [comment]
Note - this is now out of date, and pending the work we are doing with cucumber.

**Comment by krauszraphael** [comment]
N.B. I think this issue needs to be closed, we have moved back to using `npm test` rather than `npm run spec` - that test is missing.

**Comment by krauszraphael** [comment]
Also note that `npm run cucumber` is available now, and is included in the README.md in the Raphi housekeeping spike #8
