### ISSUE TITLE
Routes definitions

### ISSUE THREAD

**Issue by krauszraphael** [AgileVentures/AsyncVoter#30]
Currently in server.js we have:

``` js
app.use(require('../src/story/story.routes.js'));
```

Then in the story router we do:

``` js
router.get('/stories', controller.allStories);
router.post('/stories', controller.createStory);
```

This sets all routes to go to the story router. So we will need to then call in other routes from that file - breaking the domain model.

**Either we use something like:**

Server.js:

``` js
app.use('/stories', require('../src/story/story.routes.js'));
```

Story route:

``` js
router.get(controller.allStories);
router.post(controller.createStory);
```

**Or:**

Server.js

``` js
app.use('../src/routes.js')
```

src/routes.js

``` js
router.use('/stories', require('story/story.routes.js'));
```

Story route:

``` js
router.get(controller.allStories);
router.post(controller.createStory);
```

**Comment by sysrex** [comment]
I would suggest to use something like this

controllers = {};

and load them by

fs.readdirSync(controllers_path).forEach(function (file) {
  if (file.indexOf('.js') !== -1) {
    console.log('loading controller: ' + file);
    controllers[file.split('.')[0]] = require(controllers_path + '/' + file);
  }
});

that way we can forget about referencing each controller

**Comment by krauszraphael** [comment]
Hi @sysrex 

As discussed in the stand-up meeting, let's move the auto-loading of routes/controllers to be a separate issue.

**Comment by krauszraphael** [comment]
Added in src/routes.js

- `bin/server.js` loads `src/routes.js` for domain-level routes
- use `src/routes.js` to define domain routing
- `src/[domain]/[domain].routes.js` defines domain specific routing
- e.g. `src/routes.js` points requests to /stories to the story router at `src/story/story.routes.js`, which in turn handles the sub-level routing
