### ISSUE TITLE
Closing Voting Feature

### ISSUE THREAD

**Issue by sysrex** [AgileVentures/AsyncVoter#8]
```
Feature: Closing voting
 As a developer
 I want to be able to close voting on a specific issue
 So that I can start working on the story
```

**Comment by tansaku** [comment]
I'm not sure that it is the developer who closes the vote, but the bot that does it - I mean there could be manual override, but I imagine the bot closing the vote when consensus is achieved, i.e. 3 similar votes

**Comment by tansaku** [comment]
should we prefer:

Feature: Wrapping up voting
As a developer
I want the bot to assign points if everyone agrees, or prompt discussion and revoting to get to agreement
So that we can move on to other votes and start working on voted stories

?

**Comment by Zsuark** [comment]
Should this wait until after #63 - only active stories can be voted on?

**Comment by tansaku** [comment]
I think we need to work out what this feature is - i.e. I proposed an alternate that no one commented on ...

**Comment by arreche** [comment]
@tansaku is wondering if we could move faster by having almost no logic on the server.

So I propose closing stories manually through the API after receiving 3 votes. 

Just set the final `size` to the `story` i.e. `PUT /stories/id {"size": "1"} `

**Comment by arreche** [comment]
@tansaku proposes to adjust the spec as follows

```cucumber
Feature: Closing voting
 As an admin
 So that work can start on a story
 I want to be able to set a size on that story
```
